<script setup lang="ts">
import { computed, ref } from 'vue';import { onShow } from '@dcloudio/uni-app';import { api } from '../../api/http';import { useSessionStore } from '../../stores/session'
const store=useSessionStore();const repairs=ref<any[]>([]);const loading=ref(false);const active=ref('ALL')
const filtered=computed(()=>active.value==='ALL'?repairs.value:repairs.value.filter(i=>i.status===active.value));const statusText=(s:string)=>({PENDING:'待接单',REPAIRING:'处理中',COMPLETED:'已完成'} as any)[s]||s
async function load(){try{repairs.value=await api.technicianRepairs()}catch{}}
async function action(item:any){const isDone=item.status==='REPAIRING';loading.value=true;try{await api.technicianAction(item.id,isDone?'complete':'accept',isDone?'已完成故障排查和维修，电梯运行正常':'维修师傅已接单，正在前往现场');uni.showToast({title:isDone?'工单已完成':'接单成功',icon:'success'});await load()}finally{loading.value=false}}
async function backOwner(){await store.switchUser('owner_101');uni.switchTab({url:'/pages/home/index'})}
onShow(async()=>{await store.load();if(store.session?.role!=='TECHNICIAN'){await store.switchUser('technician_01')}await load()})
</script>
<template><view class="tech-page"><view class="tech-hero"><view class="tech-top"><view class="avatar">李</view><view><text>您好，{{ store.session?.displayName }}</text><small>维修师傅 · 本地工作台</small></view><text class="switch" @click="backOwner">切换业主</text></view><view class="stats"><view><strong>{{ repairs.filter(i=>i.status==='PENDING').length }}</strong><text>待接单</text></view><view><strong>{{ repairs.filter(i=>i.status==='REPAIRING').length }}</strong><text>处理中</text></view><view><strong>{{ repairs.filter(i=>i.status==='COMPLETED').length }}</strong><text>已完成</text></view><view><strong>2</strong><text>维保上传</text></view></view></view><view class="page content"><view class="shortcuts card"><view><text class="orange">🛠</text>工单处理</view><view @click="uni.showToast({title:'请选择 PDF 文件',icon:'none'})"><text class="green">⇧</text>维保上传</view><view @click="uni.navigateTo({url:'/pages/maintenance/index'})"><text class="blue">▣</text>维保记录</view></view><view class="section-title"><text>我的工单</text><text>{{ repairs.length }} 个</text></view><view class="tabs"><text v-for="tab in [{k:'ALL',n:'全部'},{k:'PENDING',n:'待接单'},{k:'REPAIRING',n:'处理中'},{k:'COMPLETED',n:'已完成'}]" :key="tab.k" :class="{active:active===tab.k}" @click="active=tab.k">{{ tab.n }}</text></view><view v-for="item in filtered" :key="item.id" class="work card"><view><text>工单号：{{ item.orderNo }}</text><text class="status" :class="item.status">{{ statusText(item.status) }}</text></view><strong>{{ item.house }}</strong><p>{{ item.description }}</p><small>联系人：{{ item.contactName }}　{{ item.contactPhone }}</small><view v-if="item.progressText" class="progress">{{ item.progressText }}</view><button v-if="item.status!=='COMPLETED'" class="primary-btn" :loading="loading" @click="action(item)">{{ item.status==='PENDING'?'接单处理':'提交完工' }}</button></view><view v-if="!filtered.length" class="empty">当前分类暂无工单</view></view></view></template>
<style lang="scss" scoped>.tech-page{max-width:920rpx;margin:auto;min-height:100vh;background:#f5f7fa}.tech-hero{padding:calc(var(--status-bar-height) + 25rpx) 28rpx 55rpx;background:linear-gradient(145deg,#1266ee,#347fff);color:white}.tech-top{display:flex;align-items:center;gap:16rpx}.avatar{width:76rpx;height:76rpx;border-radius:38rpx;background:#fff;color:#1768ed;display:grid;place-items:center;font-size:34rpx;font-weight:900}.tech-top>view:nth-child(2){flex:1}.tech-top text,.tech-top small{display:block}.tech-top text{font-size:31rpx;font-weight:800}.tech-top small{opacity:.75;margin-top:6rpx}.switch{font-size:20rpx!important;padding:8rpx 12rpx;border:1rpx solid #ffffff88;border-radius:18rpx}.stats{background:#fff;color:#18233a;border-radius:20rpx;display:grid;grid-template-columns:repeat(4,1fr);padding:20rpx 4rpx;margin-top:30rpx}.stats view{text-align:center;border-right:1rpx solid #edf0f5}.stats view:last-child{border:0}.stats strong,.stats text{display:block}.stats strong{font-size:34rpx;color:#1768ed}.stats text{font-size:20rpx;margin-top:5rpx}.content{margin-top:-28rpx}.shortcuts{display:grid;grid-template-columns:repeat(3,1fr);padding:24rpx}.shortcuts view{text-align:center;font-weight:700}.shortcuts text{width:65rpx;height:65rpx;border-radius:16rpx;color:#fff;display:grid;place-items:center;margin:0 auto 10rpx}.orange{background:#ff7138}.green{background:#1fbe92}.blue{background:#247bff}.tabs{display:flex;gap:16rpx;margin-bottom:16rpx}.tabs text{padding:10rpx 20rpx;background:#fff;border-radius:20rpx;color:#788396}.tabs .active{background:#1768ed;color:white}.work{padding:24rpx;margin-bottom:18rpx}.work>view:first-child{display:flex;justify-content:space-between;font-size:21rpx;color:#707b8e}.work strong{display:block;margin:17rpx 0 9rpx}.work p{margin:0 0 12rpx;color:#4f5c71}.work small{color:#8993a5}.progress{margin-top:13rpx;background:#eef5ff;color:#1768ed;padding:12rpx;border-radius:10rpx}.work button{height:68rpx;line-height:68rpx;margin-top:18rpx;font-size:24rpx}</style>

