<template>
  <WorkbenchShell role="cs" active="orders" title="订单管理" subtitle="查看客户订单，按状态处理录入、指派、结单与售后">
    <view class="filter-panel">
      <picker :range="brandOptions" range-key="label" :value="brandIndex" @change="changeBrand"><view class="filter-value">{{ brandOptions[brandIndex]?.label || '全部授权品牌' }} ▾</view></picker><text>{{ scopeHint }}</text>
      <text v-if="loading">正在加载订单…</text>
      <view class="primary-filters"><view class="search-field"><view class="search-icon"/><input v-model="keyword" class="filter-input" placeholder="搜索订单号或联系方式" @confirm="search"/></view><picker class="filter" mode="selector" :range="statusOptions" range-key="label" @change="onStatusChange"><view class="filter-value">{{ statusLabel }} ▾</view></picker><button class="search-btn" @click="search">查询</button><button class="more-btn" @click="moreOpen=!moreOpen">{{ moreOpen?'收起':'更多筛选' }}</button></view>
      <view v-if="moreOpen" class="more-filters"><input v-model="game" class="filter-input" placeholder="游戏名称"/><input v-model="serviceType" class="filter-input" placeholder="服务类型"/><picker mode="date" :value="fromDate" @change="fromDate=$event.detail.value"><view class="date-picker">{{ fromDate||'开始日期' }} ▾</view></picker><picker mode="date" :value="toDate" @change="toDate=$event.detail.value"><view class="date-picker">{{ toDate||'结束日期' }} ▾</view></picker><button class="reset-btn" @click="reset">重置</button></view>
    </view>
    <view v-if="error" class="error-box"><text>{{ error }}</text><button @click="search">重新加载</button></view>
    <view class="result-bar"><text>订单列表</text><text>共 {{ orders.length }} 条</text></view>
    <view v-if="orders.length" class="table-card">
      <view class="table-row table-head"><text>订单与商品</text><text>客户需求</text><text>状态</text><text>金额</text><text>接单人员</text><text>操作</text></view>
      <view v-for="order in orders" :key="oid(order)" class="table-row order-card" @click="openDetail(order)">
        <view class="order-primary"><text class="order-title">{{ order.productTitle||productName(order) }}</text><text class="order-no">{{ order.orderNo }}</text></view>
        <view class="order-meta"><text>{{ gameText(order.game) }} · {{ serviceTypeText(order.serviceType) }}</text><text>{{ formatDateTime(order.expectStartAt||order.createdAt) }}</text></view>
        <text class="order-status" :class="statusTone(order.status)">{{ orderStatusText(order.status) }}</text><text class="order-amount">¥{{ fenToYuan(order.amountFen) }}</text><text class="worker">{{ order.workerName||order.workerId||'未接单' }}</text><button class="detail-btn" @click.stop="openDetail(order)">查看详情</button>
      </view>
    </view>
    <view v-if="!error&&orders.length===0" class="empty"><view class="empty-mark"><view class="empty-shape"/></view><text>暂无符合条件的订单</text><button @click="reset">清除筛选</button></view>
  </WorkbenchShell>
</template>

<script setup>
import { sessionStore } from '../../session.js';
import { computed,ref } from 'vue'; import { onLoad, onShow } from '@dcloudio/uni-app'; import { api, getActiveBrandId, setActiveBrandId } from '../../api.js'; import { guard,oid,fenToYuan,orderStatusText } from '../../common.js'; import { gameText,serviceTypeText,formatDateTime } from '../../utils/display.js'; import WorkbenchShell from '../../components/WorkbenchShell.vue';
const statusOptions=[{value:'',label:'全部状态'},{value:'PENDING_PAYMENT',label:'待支付'},{value:'PENDING_ACCEPT',label:'待受理'},{value:'PENDING_GRAB',label:'待抢单'},{value:'ASSIGN_PENDING',label:'待指派确认'},{value:'IN_SERVICE',label:'服务中'},{value:'PENDING_CONFIRM',label:'待验收'},{value:'SETTLED',label:'已结单'},{value:'DISPUTING',label:'异议中'},{value:'CANCELLED',label:'已取消'},{value:'REFUNDING',label:'退款中'},{value:'REFUNDED',label:'已退款'},{value:'CLOSED',label:'已关闭'}];
const profile=ref({});const brandIndex=ref(0);const loading=ref(false);
const brandOptions=computed(()=>[{brandId:'',label:'全部授权品牌'},...(profile.value.brands||[]).map(b=>({...b,label:`${b.name}（${b.brandId}）`}))]);
const scopeHint=computed(()=>profile.value.scopeHint || `授权范围：${(profile.value.brandScopes||[]).includes('*')?'所有品牌':(profile.value.brandScopes||[]).join('、')||'仅历史 default'}`);
async function changeBrand(e){brandIndex.value=Number(e.detail.value);setActiveBrandId(brandOptions.value[brandIndex.value]?.brandId||'');await search();}
const status=ref('');const game=ref('');const serviceType=ref('');const keyword=ref('');const fromDate=ref('');const toDate=ref('');const orders=ref([]);const error=ref('');const moreOpen=ref(false);const statusLabel=computed(()=>statusOptions.find((item)=>item.value===status.value)?.label||'全部状态');
function productName(order){const snap=order.productSnapshot||{};return snap.title||snap.name||'服务订单';}function onStatusChange(event){status.value=statusOptions[Number(event.detail.value)].value;search();}
function buildFilters(){const value={};if(status.value)value.status=status.value;if(game.value)value.game=game.value;if(serviceType.value)value.serviceType=serviceType.value;if(keyword.value)value.keyword=keyword.value.trim();if(fromDate.value)value.from=new Date(`${fromDate.value}T00:00:00`).getTime();if(toDate.value)value.to=new Date(`${toDate.value}T23:59:59`).getTime();return value;}
let searchVersion=0;
async function search(){const version=++searchVersion;loading.value=true;error.value='';try{const list=await api.listOrders(buildFilters());if(!Array.isArray(list))throw new Error('订单接口返回格式异常，请更新 game-service 后重试');if(version===searchVersion)orders.value=list;}catch(e){if(version===searchVersion){error.value=e.message||'订单加载失败';orders.value=[];}}finally{if(version===searchVersion)loading.value=false;}}
function reset(){status.value='';game.value='';serviceType.value='';keyword.value='';fromDate.value='';toDate.value='';search();}
function statusTone(value){if(['SETTLED'].includes(value))return'success';if(['REFUNDING','DISPUTING'].includes(value))return'warning';if(['CANCELLED','REFUNDED','CLOSED'].includes(value))return'muted';return'active';}
function openDetail(order){uni.navigateTo({url:`/pages/cs/order-detail?orderId=${encodeURIComponent(oid(order))}`});}
onLoad((query)=>{if(query&&query.status)status.value=query.status;});
onShow(async()=>{if(!guard(['CS']))return;try{profile.value=await api.getAccessProfile();sessionStore.set('accessProfile',profile.value);brandIndex.value=Math.max(0,brandOptions.value.findIndex(b=>b.brandId===getActiveBrandId()));setActiveBrandId(brandOptions.value[brandIndex.value].brandId);await search();}catch(e){error.value=e.message||'权限信息加载失败';}});
</script>

<style lang="scss" scoped>
.filter-panel{margin-bottom:18px;padding:16px;background:#fff;border:1px solid var(--es-border-soft);border-radius:12px}.primary-filters,.more-filters{display:flex;align-items:center;gap:10px}.search-field{height:40px;min-width:260px;flex:1;display:flex;align-items:center;gap:10px;padding:0 12px;border:1px solid var(--es-border);border-radius:9px}.search-icon{width:13px;height:13px;position:relative;border:2px solid #98a2b3;border-radius:50%}.search-icon::after{content:'';position:absolute;right:-5px;bottom:-3px;width:6px;height:2px;background:#98a2b3;transform:rotate(45deg)}.filter-input{min-width:0;height:38px;padding:0;border:0;color:var(--es-text);font-size:13px;background:#fff!important}.filter-value,.date-picker{height:40px;min-width:130px;padding:0 12px;display:flex;align-items:center;color:var(--es-text);font-size:13px;background:#fff;border:1px solid var(--es-border);border-radius:9px}.search-btn,.more-btn,.reset-btn{width:auto;height:40px;margin:0;padding:0 16px;font-size:13px;line-height:40px;border-radius:9px}.search-btn{color:#fff;font-weight:600;background:var(--es-primary)}.more-btn,.reset-btn{color:var(--es-text-dim);background:#fff;border:1px solid var(--es-border)}.more-filters{margin-top:12px;padding-top:12px;border-top:1px solid var(--es-border-soft)}.more-filters>.filter-input{height:40px;padding:0 12px;border:1px solid var(--es-border)!important;border-radius:9px}.more-filters>picker{flex:1}.more-filters .date-picker{width:100%}
.result-bar{margin:0 2px 10px;display:flex;justify-content:space-between}.result-bar text:first-child{font-size:15px;font-weight:700}.result-bar text:last-child{color:var(--es-text-dim);font-size:12px}.table-card{overflow:hidden;background:#fff;border:1px solid var(--es-border-soft);border-radius:12px}.table-row{min-height:70px;padding:10px 16px;display:grid;grid-template-columns:minmax(210px,1.5fr) minmax(190px,1.3fr) 110px 100px minmax(120px,1fr) 86px;align-items:center;gap:14px;border-bottom:1px solid var(--es-border-soft)}.table-row:last-child{border-bottom:0}.table-head{min-height:44px;color:var(--es-text-dim);font-size:12px;font-weight:600;background:#f8f9fc}.order-card{margin:0;cursor:pointer}.order-card:hover{background:#fafbff}.order-primary text,.order-meta text{display:block}.order-title{overflow:hidden;font-size:14px;font-weight:600;text-overflow:ellipsis;white-space:nowrap}.order-no,.order-meta text:last-child{margin-top:5px;color:var(--es-text-dim);font-size:11px}.order-meta{color:var(--es-text-dim);font-size:12px}.order-status{width:max-content;padding:5px 9px;color:#4338ca;font-size:11px;font-weight:600;background:#eef0ff;border-radius:999px}.order-status.success{color:#027a48;background:#ecfdf3}.order-status.warning{color:#b54708;background:#fffaeb}.order-status.muted{color:#475467;background:#f2f4f7}.order-amount{font-size:14px;font-weight:700}.worker{overflow:hidden;color:var(--es-text-dim);font-size:12px;text-overflow:ellipsis;white-space:nowrap}.detail-btn{width:auto;height:32px;margin:0;padding:0 10px;color:var(--es-primary);font-size:12px;line-height:32px;background:#fff;border:1px solid #c7d7fe;border-radius:8px}.error-box{margin-bottom:14px;padding:12px 14px;display:flex;align-items:center;justify-content:space-between;color:#b42318;font-size:12px;background:#fef3f2;border:1px solid #fecdca;border-radius:9px}.error-box button,.empty button{width:auto;height:32px;margin:0;padding:0 12px;color:var(--es-primary);font-size:12px;line-height:32px;background:#fff;border:1px solid #c7d7fe;border-radius:8px}.empty{min-height:320px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:14px;color:var(--es-text-dim);font-size:14px;background:#fff;border:1px solid var(--es-border-soft);border-radius:12px}.empty-mark{width:58px;height:58px;display:flex;align-items:center;justify-content:center;background:#eef0ff;border-radius:18px}.empty-mark i{width:22px;height:22px;border:3px solid var(--es-primary);border-radius:50%}
@media(max-width:900px){.table-row{grid-template-columns:minmax(180px,1.4fr) minmax(150px,1fr) 95px 90px 80px}.table-row>.worker{display:none}.table-head text:nth-child(5){display:none}}
@media(max-width:767px){.primary-filters{flex-wrap:wrap}.search-field{min-width:100%;order:0}.filter{flex:1}.filter-value{width:100%}.search-btn{flex:1}.more-btn{width:100%;order:4}.more-filters{flex-wrap:wrap}.more-filters>*{min-width:calc(50% - 6px);flex:1}.table-head{display:none}.table-card{border:0;background:transparent}.table-row{margin-bottom:12px;padding:15px;display:grid;grid-template-columns:1fr auto;gap:8px 12px;background:#fff;border:1px solid var(--es-border-soft)!important;border-radius:12px}.order-primary{grid-column:1}.order-status{grid-column:2;grid-row:1}.order-meta{grid-column:1/-1}.order-amount{grid-column:1}.worker{display:block!important;grid-column:1;color:var(--es-text-dim)}.detail-btn{grid-column:2;grid-row:3/5;align-self:end}.result-bar{margin-top:4px}}
.empty-shape{width:22px;height:22px;border:3px solid var(--es-primary);border-radius:50%}
</style>
