<template>
  <WorkbenchShell role="worker" active="pool" title="订单池" :subtitle="`当前进行中 ${activeCount}/${maxActive} 单，新订单每 ${pollSeconds} 秒自动刷新`">
    <template #actions><view class="capacity" :class="{full:activeCount>=maxActive}"><view class="capacity-dot"/><text>{{ activeCount>=maxActive?'当前容量已满':'可以继续接单' }}</text><text v-if="newOrderBadge" class="new-badge">{{ newOrderBadge }} 笔新单</text></view></template>
    <view v-if="error" class="error-box"><text>{{ error }}</text><button @click="load">重新加载</button></view>
    <view v-if="assignments.length" class="assignment-panel"><view class="panel-title"><view><text>待确认指派</text><text>客服为你指派了 {{ assignments.length }} 笔订单</text></view></view><view v-for="order in assignments" :key="oid(order)" class="assignment-row"><view><text>{{ order.productTitle||productName(order) }}</text><text>{{ order.orderNo }} · {{ gameText(order.game) }} · {{ serviceTypeText(order.serviceType) }}</text></view><view class="assignment-actions"><button v-if="can(order,'rejectAssignment')" class="danger-btn" @click="openReject(order)">拒绝</button><button v-if="can(order,'acceptAssignment')" class="primary-btn" @click="doAccept(order)">接受指派</button></view></view><view v-if="rejectTarget" class="reject-box"><textarea v-model="rejectReason" class="textarea" placeholder="请填写拒绝原因"/><view><button class="secondary-btn" @click="rejectTarget=null">取消</button><button class="danger-btn" @click="doReject">确认拒绝</button></view></view></view>
    <view class="pool-head"><view><text>可接订单</text><text>共 {{ pool.length }} 单</text></view><button @click="load">刷新订单</button></view>
    <view v-if="pool.length" class="pool-grid"><view v-for="order in pool" :key="oid(order)" class="order-card">
      <view class="order-head"><view><text class="order-title">{{ order.productTitle||productName(order) }}</text><text class="order-no">{{ order.orderNo }}</text></view><text class="order-amount">¥{{ fenToYuan(order.amountFen) }}</text></view>
      <view class="tags"><text>{{ gameText(order.game) }}</text><text>{{ order.region||'区服待确认' }}</text><text>{{ serviceTypeText(order.serviceType) }}</text></view>
      <view class="order-details"><view><text>服务保障</text><text>{{ order.guaranteedOutput??'—' }}{{ order.outputUnit||'' }}</text></view><view><text>期望开始</text><text>{{ formatDateTime(order.expectStartAt) }}</text></view></view>
      <view class="order-footer"><text v-if="activeCount>=maxActive">完成当前订单后可继续接单</text><text v-else>接单后请及时联系客户并开始服务</text><button v-if="can(order,'grabOrder')" class="primary-btn" :disabled="activeCount>=maxActive" @click="doGrab(order)">{{ activeCount>=maxActive?'容量已满':'立即抢单' }}</button></view>
    </view></view>
    <view v-if="!error&&pool.length===0&&assignments.length===0" class="empty"><view class="empty-icon"><view class="empty-shape"/></view><text>暂时没有可接订单</text><text>新订单进入后会自动提醒你</text></view>
  </WorkbenchShell>
</template>

<script setup>
import { ref } from 'vue';import { onLoad,onUnload } from '@dcloudio/uni-app';import { api } from '../../api.js';import { guard,oid,fenToYuan,playBeep,startPoll } from '../../common.js';import { gameText,serviceTypeText,formatDateTime } from '../../utils/display.js';import WorkbenchShell from '../../components/WorkbenchShell.vue';
const maxActive=ref(3);const pollSeconds=ref(10);const newOrderBadge=ref(0);const pool=ref([]);const assignments=ref([]);const activeCount=ref(0);const error=ref('');const can=(order,action)=>Array.isArray(order&&order.allowedActions)&&order.allowedActions.includes(action);const rejectTarget=ref(null);const rejectReason=ref('');let stop=null;let prevIds=[];
function productName(order){const snapshot=order.productSnapshot||{};return snapshot.title||snapshot.name||'服务订单';}
async function load(){error.value='';try{const[poolList,myOrders]=await Promise.all([api.listPool(),api.listMyOrders()]);const list=Array.isArray(poolList)?poolList:[];const mine=Array.isArray(myOrders)?myOrders:[];const ids=list.map((order)=>oid(order));const added=prevIds.length?ids.filter((id)=>!prevIds.includes(id)).length:0;if(added){newOrderBadge.value+=added;playBeep();}prevIds=ids;pool.value=list;assignments.value=mine.filter((order)=>order.status==='ASSIGN_PENDING');activeCount.value=mine.filter((order)=>['IN_SERVICE','PENDING_CONFIRM'].includes(order.status)).length;}catch(e){error.value=e.message||'订单池加载失败';}}
async function doGrab(order){newOrderBadge.value=0;if(activeCount.value>=maxActive.value){uni.showToast({title:`同时进行订单已达上限 ${maxActive.value} 单`,icon:'none'});return;}try{await api.grabOrder(oid(order),order.version||0);uni.showToast({title:'抢单成功',icon:'success'});load();}catch(e){uni.showToast({title:e.code==='CONFLICT'?'订单已被处理，正在刷新':(e.message||'抢单失败'),icon:'none'});if(e.code==='CONFLICT')load();}}
async function doAccept(order){try{await api.acceptAssignment(oid(order));uni.showToast({title:'已接受指派',icon:'success'});load();}catch(e){uni.showToast({title:e.message||'操作失败',icon:'none'});}}function openReject(order){rejectTarget.value=order;rejectReason.value='';}
async function doReject(){if(!rejectTarget.value)return;try{await api.rejectAssignment(oid(rejectTarget.value),rejectReason.value||'拒绝指派');uni.showToast({title:'已拒绝',icon:'success'});rejectTarget.value=null;load();}catch(e){uni.showToast({title:e.message||'操作失败',icon:'none'});}}
onLoad(async()=>{if(!guard(['WORKER']))return;try{const config=await api.getRuntimeConfig();maxActive.value=Number(config.maxActiveOrders)||3;pollSeconds.value=Number(config.pollIntervalSeconds)||10;}catch(e){/* 安全默认值；后端仍最终校验接单上限 */}stop=startPoll(load,pollSeconds.value*1000);});onUnload(()=>{if(stop)stop();});
</script>

<style lang="scss" scoped>
.capacity{height:36px;padding:0 12px;display:flex;align-items:center;gap:8px;color:#027a48;font-size:12px;font-weight:600;background:#ecfdf3;border-radius:9px}.capacity span{width:8px;height:8px;background:var(--es-success);border-radius:50%}.capacity.full{color:#b54708;background:#fffaeb}.capacity.full span{background:var(--es-warning)}.error-box{margin-bottom:14px;padding:12px 14px;display:flex;justify-content:space-between;color:#b42318;font-size:12px;background:#fef3f2;border:1px solid #fecdca;border-radius:9px}.error-box button,.pool-head button{width:auto;height:32px;margin:0;padding:0 12px;color:var(--es-primary);font-size:12px;line-height:32px;background:#fff;border:1px solid #c7d7fe;border-radius:8px}
.assignment-panel{margin-bottom:18px;padding:20px;background:#fff;border:1px solid #fedf89;border-left:4px solid var(--es-warning);border-radius:12px}.panel-title text{display:block}.panel-title text:first-child{font-size:16px;font-weight:700}.panel-title text:last-child{margin-top:4px;color:var(--es-text-dim);font-size:12px}.assignment-row{padding:16px 0;display:flex;align-items:center;justify-content:space-between;gap:16px;border-bottom:1px solid var(--es-border-soft)}.assignment-row>view:first-child text{display:block}.assignment-row>view:first-child text:first-child{font-size:14px;font-weight:600}.assignment-row>view:first-child text:last-child{margin-top:5px;color:var(--es-text-dim);font-size:11px}.assignment-actions{display:flex;gap:8px}.primary-btn,.secondary-btn,.danger-btn{width:auto;height:38px;margin:0;padding:0 16px;font-size:13px;line-height:38px;border-radius:9px}.primary-btn{color:#fff;font-weight:600;background:var(--es-primary)}.primary-btn[disabled]{opacity:.5}.secondary-btn{color:var(--es-text-dim);background:#fff;border:1px solid var(--es-border)}.danger-btn{color:#b42318;background:#fff;border:1px solid #fda29b}.reject-box{padding-top:14px}.textarea{width:100%;height:90px;padding:12px;color:var(--es-text);font-size:13px;background:#fff!important;border:1px solid var(--es-border);border-radius:9px}.reject-box>view{margin-top:10px;display:flex;justify-content:flex-end;gap:8px}
.pool-head{margin:0 2px 12px;display:flex;align-items:center;justify-content:space-between}.pool-head>view{display:flex;align-items:baseline;gap:8px}.pool-head>view text:first-child{font-size:16px;font-weight:700}.pool-head>view text:last-child{color:var(--es-text-dim);font-size:12px}.pool-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.order-card{padding:20px;background:#fff;border:1px solid var(--es-border-soft);border-radius:14px;box-shadow:var(--es-glow);transition:transform .18s ease,box-shadow .18s ease}.order-card:hover{transform:translateY(-2px);box-shadow:0 10px 28px rgba(16,24,40,.09)}.order-head{display:flex;justify-content:space-between;gap:12px}.order-head text{display:block}.order-title{font-size:16px;font-weight:700}.order-no{margin-top:5px;color:var(--es-text-dim);font-size:11px}.order-amount{color:var(--es-primary);font-size:20px;font-weight:700}.tags{margin-top:14px;display:flex;flex-wrap:wrap;gap:7px}.tags text{padding:4px 8px;color:#4338ca;font-size:11px;background:#eef0ff;border-radius:999px}.order-details{margin-top:16px;padding:14px;display:grid;grid-template-columns:1fr 1.4fr;gap:12px;background:#f8f9fc;border-radius:9px}.order-details text{display:block}.order-details text:first-child{color:var(--es-text-dim);font-size:11px}.order-details text:last-child{margin-top:4px;font-size:13px;font-weight:500}.order-footer{margin-top:16px;padding-top:16px;display:flex;align-items:center;justify-content:space-between;gap:12px;border-top:1px solid var(--es-border-soft)}.order-footer>text{color:var(--es-text-dim);font-size:11px}.empty{min-height:340px;display:flex;flex-direction:column;align-items:center;justify-content:center;color:var(--es-text-dim);background:#fff;border:1px solid var(--es-border-soft);border-radius:14px}.empty>text:nth-child(2){margin-top:14px;color:var(--es-text);font-size:15px;font-weight:600}.empty>text:last-child{margin-top:6px;font-size:12px}.empty-icon{width:64px;height:64px;display:flex;align-items:center;justify-content:center;background:#eef0ff;border-radius:20px}.empty-icon i{width:24px;height:24px;border:3px solid var(--es-primary);border-radius:7px}
@media(max-width:950px){.pool-grid{grid-template-columns:1fr}}@media(max-width:767px){.assignment-row{align-items:flex-start;flex-direction:column}.assignment-actions{width:100%}.assignment-actions button{flex:1}.order-card{padding:16px}.order-footer{align-items:flex-end}.order-footer .primary-btn{min-width:112px}.pool-grid{gap:12px}}
.capacity-dot{width:8px;height:8px;background:var(--es-success);border-radius:50%}.capacity.full .capacity-dot{background:var(--es-warning)}.empty-shape{width:24px;height:24px;border:3px solid var(--es-primary);border-radius:7px}
.new-badge{margin-left:6px;padding:2px 7px;color:#fff;background:var(--es-danger);border-radius:999px}
</style>
