<template>
  <WorkbenchShell role="worker" active="profile" title="个人资料" subtitle="维护实名与收款信息；敏感资料默认脱敏，修改后重新进入审核">
    <template #actions><view class="status-chip" :class="statusTone"><view class="status-dot"/><text>{{ realnameStatusText(realnameStatus) }}</text></view></template>
    <view v-if="mustChangePwd" class="first-login-alert"><view class="alert-icon">!</view><view><text>首次登录必须修改初始密码</text><text>新密码需 12–128 位，并满足大写、小写、数字、特殊字符中的至少 3 类。</text></view><button @click="focusPassword">立即修改</button></view>
    <view class="profile-grid">
      <view class="main-column"><view class="panel identity-panel">
        <view class="panel-head"><view><text class="panel-title">实名与收款资料</text><text class="panel-desc">资料仅用于身份核验和佣金提现</text></view><text class="privacy-tag">隐私保护中</text></view>
        <view class="status-banner" :class="statusTone"><view class="status-badge">{{ statusMark }}</view><view><text>{{ statusHeadline }}</text><text>{{ statusDescription }}</text></view></view>
        <view class="saved-grid"><view><text>登录手机号</text><text>{{ maskPhone(user.phone) || '未绑定' }}</text></view><view><text>实名姓名</text><text>{{ savedRealName }}</text></view><view><text>收款微信</text><text>{{ savedWechat }}</text></view><view><text>身份证材料</text><text>{{ hasIdCard ? '已提交（不可直接查看）' : '尚未提交' }}</text></view></view>
        <view class="form-section"><text class="section-label">更新资料</text><view class="field-grid"><label class="field"><text>实名姓名</text><input v-model="realName" class="input" placeholder="填写新姓名；不修改可留空" /></label><label class="field"><text>收款微信号</text><input v-model="withdrawWechat" class="input" placeholder="填写新微信号；不修改可留空" /></label></view>
          <view class="upload-field"><view><text>身份证正面截图</text><text>仅管理员审核可见，列表和本页不展示原始证件内容</text></view><view v-if="idCardImage" class="preview-wrap"><image class="thumb blurred" :src="idCardImage" mode="aspectFill"/><view class="privacy-mask">已遮罩</view><button aria-label="移除待上传图片" @click="removeIdCard">×</button></view><button v-else class="upload-button" @click="chooseIdCard"><text>＋</text><text>选择身份证截图</text><text>JPG/PNG，单张上传</text></button></view>
          <view class="form-actions"><text>提交后实名状态将变为待审核</text><button class="primary-btn" :disabled="busy" @click="doUpdateProfile">{{ busy ? '提交中…' : '提交审核' }}</button></view>
        </view>
      </view></view>
      <view class="side-column"><view ref="passwordPanel" class="panel password-panel" :class="{ attention: mustChangePwd }"><view class="panel-head"><view><text class="panel-title">{{ mustChangePwd ? '设置新密码' : '修改密码' }}</text><text class="panel-desc">修改成功后需使用新密码重新登录</text></view></view><label class="field"><text>当前密码</text><input v-model="oldPassword" class="input" password placeholder="请输入当前密码" /></label><label class="field"><text>新密码</text><input v-model="newPassword" class="input" password placeholder="12–128 位，至少满足 3 类字符" /></label><label class="field"><text>确认新密码</text><input v-model="confirmPassword" class="input" password placeholder="再次输入新密码" /></label><view class="password-rules"><text :class="{ok:newPassword.length>=12&&newPassword.length<=128}">12–128 位</text><text :class="{ok:passwordClassCount(newPassword)>=3}">大写/小写/数字/特殊字符至少 3 类</text></view><button class="secondary-btn" :disabled="busy" @click="doChangePassword">确认修改密码</button></view><view class="security-note"><text>安全提示</text><text>平台不会通过客服索要密码、验证码或身份证原图。发现异常请立即修改密码并联系客服。</text></view></view>
    </view>
  </WorkbenchShell>
</template>

<script setup>
import { computed, ref } from 'vue';
import { onLoad } from '@dcloudio/uni-app';
import { api, uploadFile } from '../../api.js';
import { confirmAction, getSession, guard, realnameStatusText } from '../../common.js';
import { maskName, maskPhone, maskWechat } from '../../utils/display.js';
import WorkbenchShell from '../../components/WorkbenchShell.vue';

const user=ref({});const profile=ref({});const realnameStatus=ref('');const withdrawWechat=ref('');const realName=ref('');const idCardImage=ref('');const idCardAttachmentId=ref('');const oldPassword=ref('');const newPassword=ref('');const confirmPassword=ref('');const busy=ref(false);const mustChangePwd=ref(false);const passwordPanel=ref(null);
const normalizedStatus=computed(()=>realnameStatus.value==='PENDING_REVIEW'?'PENDING':(realnameStatus.value||'UNSUBMITTED'));
const statusTone=computed(()=>({APPROVED:'approved',PENDING:'pending',REJECTED:'rejected'}[normalizedStatus.value]||'unsubmitted'));
const statusMark=computed(()=>({APPROVED:'✓',PENDING:'…',REJECTED:'!',UNSUBMITTED:'i'}[normalizedStatus.value]||'i'));
const statusHeadline=computed(()=>({APPROVED:'实名认证已通过',PENDING:'实名认证审核中',REJECTED:'实名认证未通过',UNSUBMITTED:'尚未提交实名认证'}[normalizedStatus.value]));
const statusDescription=computed(()=>({APPROVED:'可以正常申请提现；修改实名材料后需重新审核。',PENDING:'管理员正在核验资料，审核期间暂不可发起新提现。',REJECTED:'请核对姓名与身份证材料后重新提交。',UNSUBMITTED:'完成实名资料后才能申请佣金提现。'}[normalizedStatus.value]));
const savedRealName=computed(()=>maskName(profile.value.realName||user.value.profile?.realName));const savedWechat=computed(()=>maskWechat(profile.value.withdrawWechat||user.value.profile?.withdrawWechat));const hasIdCard=computed(()=>!!(profile.value.hasIdCard||profile.value.idCardAttachmentId||user.value.profile?.idCardAttachmentId));

async function loadProfile(){const{user:sessionUser}=getSession();user.value=sessionUser||{};const fallback=sessionUser?.profile||{};try{profile.value=(await api.getProfile())||{};}catch(_error){profile.value=fallback;}realnameStatus.value=profile.value.realnameStatus||sessionUser?.realnameStatus||fallback.realnameStatus||'UNSUBMITTED';}
function chooseIdCard(){uni.chooseImage({count:1,success:(res)=>{idCardImage.value=res.tempFilePaths?.[0]||'';idCardAttachmentId.value='';}});}function removeIdCard(){idCardImage.value='';idCardAttachmentId.value='';}function focusPassword(){const target=passwordPanel.value?.$el||passwordPanel.value;target?.scrollIntoView?.({behavior:'smooth',block:'center'});}
async function doUpdateProfile(){if(!realName.value.trim()&&!withdrawWechat.value.trim()&&!idCardImage.value){uni.showToast({title:'请填写或选择需要更新的资料',icon:'none'});return;}const confirmed=await confirmAction({title:'确认提交实名资料',content:'提交后资料将进入管理员审核，身份证图片不会在列表中明文展示。',confirmText:'确认提交'});if(!confirmed)return;busy.value=true;try{let attachmentId=idCardAttachmentId.value;if(idCardImage.value&&!attachmentId){const upload=await uploadFile('id_card',idCardImage.value,idCardImage.value.split('/').pop()||'id-card.jpg');attachmentId=upload.attachmentId||upload.attachment_id||upload.id;}await api.updateProfile({...(withdrawWechat.value.trim()?{withdrawWechat:withdrawWechat.value.trim()}:{}),...(realName.value.trim()?{realName:realName.value.trim()}:{}),...(attachmentId?{idCardAttachmentId:attachmentId}:{})});realName.value='';withdrawWechat.value='';idCardImage.value='';idCardAttachmentId.value='';await loadProfile();uni.showToast({title:'已提交，待管理员审核',icon:'success'});}catch(error){uni.showToast({title:error.message||'保存失败',icon:'none'});}finally{busy.value=false;}}
function passwordClassCount(value){return [/[A-Z]/,/[a-z]/,/\d/,/[^A-Za-z0-9]/].filter((rule)=>rule.test(value||'')).length;}
async function doChangePassword(){if(!oldPassword.value||!newPassword.value){uni.showToast({title:'请填写当前密码与新密码',icon:'none'});return;}if(newPassword.value.length<12||newPassword.value.length>128||passwordClassCount(newPassword.value)<3){uni.showToast({title:'新密码需 12–128 位且至少满足 3 类字符',icon:'none'});return;}if(newPassword.value!==confirmPassword.value){uni.showToast({title:'两次输入的新密码不一致',icon:'none'});return;}busy.value=true;try{await api.changePassword({oldPassword:oldPassword.value,newPassword:newPassword.value});oldPassword.value='';newPassword.value='';confirmPassword.value='';uni.removeStorageSync('mustChangePwd');mustChangePwd.value=false;uni.removeStorageSync('token');uni.removeStorageSync('user');uni.removeStorageSync('accessProfile');uni.showModal({title:'密码修改成功',content:'为保护账号安全，请使用新密码重新登录。',showCancel:false,success:()=>uni.reLaunch({url:'/pages/login/index'})});}catch(error){uni.showToast({title:error.message||'修改失败',icon:'none'});}finally{busy.value=false;}}
onLoad(()=>{if(!guard(['WORKER']))return;mustChangePwd.value=!!uni.getStorageSync('mustChangePwd');loadProfile();});
</script>

<style lang="scss" scoped>
.status-chip{height:36px;padding:0 12px;display:flex;align-items:center;gap:8px;color:#475467;font-size:12px;font-weight:600;background:#f2f4f7;border-radius:999px}.status-dot{width:8px;height:8px;background:#98a2b3;border-radius:50%}.status-chip.approved{color:#027a48;background:#ecfdf3}.status-chip.approved .status-dot{background:var(--es-success)}.status-chip.pending{color:#b54708;background:#fffaeb}.status-chip.pending .status-dot{background:var(--es-warning)}.status-chip.rejected{color:#b42318;background:#fef3f2}.status-chip.rejected .status-dot{background:var(--es-danger)}
.first-login-alert{margin-bottom:18px;padding:16px 18px;display:flex;align-items:center;gap:13px;background:#fff7ed;border:1px solid #fed7aa;border-radius:12px}.alert-icon{width:32px;height:32px;flex:none;display:flex;align-items:center;justify-content:center;color:#fff;font-weight:800;background:#f97316;border-radius:50%}.first-login-alert>view:nth-child(2){min-width:0;flex:1}.first-login-alert text{display:block}.first-login-alert text:first-child{font-size:14px;font-weight:700}.first-login-alert text:last-child{margin-top:4px;color:#9a3412;font-size:12px}.first-login-alert button{width:auto;height:34px;margin:0;padding:0 13px;color:#9a3412;font-size:12px;line-height:34px;background:#fff;border:1px solid #fdba74;border-radius:8px}
.profile-grid{display:grid;grid-template-columns:minmax(0,1.65fr) minmax(290px,.75fr);gap:18px}.panel{padding:22px;background:#fff;border:1px solid var(--es-border-soft);border-radius:14px;box-shadow:var(--es-glow)}.panel-head{margin-bottom:18px;display:flex;align-items:flex-start;justify-content:space-between;gap:12px}.panel-title,.panel-desc{display:block}.panel-title{font-size:16px;font-weight:700}.panel-desc{margin-top:5px;color:var(--es-text-dim);font-size:12px}.privacy-tag{padding:5px 9px;color:#4338ca;font-size:11px;background:#eef0ff;border-radius:999px}
.status-banner{padding:15px;display:flex;gap:12px;background:#f8fafc;border:1px solid #e4e7ec;border-radius:11px}.status-badge{width:34px;height:34px;flex:none;display:flex;align-items:center;justify-content:center;color:#475467;font-size:16px;font-weight:800;background:#fff;border-radius:50%;box-shadow:0 1px 2px rgba(16,24,40,.08)}.status-banner text{display:block}.status-banner text:first-child{font-size:14px;font-weight:700}.status-banner text:last-child{margin-top:4px;color:var(--es-text-dim);font-size:12px;line-height:1.5}.status-banner.approved{background:#ecfdf3;border-color:#abefc6}.status-banner.approved .status-badge{color:#027a48}.status-banner.pending{background:#fffaeb;border-color:#fedf89}.status-banner.pending .status-badge{color:#b54708}.status-banner.rejected{background:#fef3f2;border-color:#fecdca}.status-banner.rejected .status-badge{color:#b42318}
.saved-grid{margin:18px 0;display:grid;grid-template-columns:1fr 1fr;border:1px solid var(--es-border-soft);border-radius:11px;overflow:hidden}.saved-grid>view{min-height:74px;padding:14px 16px;border-right:1px solid var(--es-border-soft);border-bottom:1px solid var(--es-border-soft)}.saved-grid>view:nth-child(2n){border-right:0}.saved-grid>view:nth-last-child(-n+2){border-bottom:0}.saved-grid text{display:block}.saved-grid text:first-child{color:var(--es-text-dim);font-size:11px}.saved-grid text:last-child{margin-top:7px;font-size:13px;font-weight:600}.form-section{padding-top:18px;border-top:1px solid var(--es-border-soft)}.section-label{display:block;margin-bottom:14px;font-size:14px;font-weight:700}.field-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.field{display:block}.field>text,.upload-field>view:first-child text{display:block;margin-bottom:7px;color:#344054;font-size:12px;font-weight:600}.input{width:100%;height:42px;padding:0 12px;color:var(--es-text);font-size:13px;background:#fff!important;border:1px solid var(--es-border)!important;border-radius:9px}.upload-field{margin-top:15px}.upload-field>view:first-child text:last-child{margin-top:-3px;color:var(--es-text-dim);font-size:11px;font-weight:400}.upload-button{width:100%;height:94px;margin:10px 0 0;display:flex;flex-direction:column;align-items:center;justify-content:center;color:var(--es-text-dim);font-size:11px;line-height:1.5;background:#fafbff;border:1px dashed #aeb4fd;border-radius:10px}.upload-button text:first-child{color:var(--es-primary);font-size:22px}.upload-button text:nth-child(2){color:var(--es-text);font-size:12px;font-weight:600}.preview-wrap{width:150px;height:94px;margin-top:10px;position:relative;overflow:hidden;border-radius:10px}.thumb{width:100%;height:100%}.blurred{filter:blur(7px);transform:scale(1.08)}.privacy-mask{position:absolute;inset:0;display:flex;align-items:center;justify-content:center;color:#fff;font-size:12px;font-weight:700;background:rgba(15,23,42,.52)}.preview-wrap button{position:absolute;right:5px;top:5px;width:24px;height:24px;margin:0;padding:0;color:#fff;line-height:24px;background:rgba(15,23,42,.75);border-radius:50%}.form-actions{margin-top:18px;display:flex;align-items:center;justify-content:space-between;gap:16px}.form-actions>text{color:var(--es-text-dim);font-size:11px}.primary-btn,.secondary-btn{width:auto;height:40px;margin:0;padding:0 18px;font-size:13px;line-height:40px;border-radius:9px}.primary-btn{color:#fff;font-weight:600;background:var(--es-primary)}.primary-btn[disabled],.secondary-btn[disabled]{opacity:.5}
.side-column{display:flex;flex-direction:column;gap:14px}.password-panel.attention{border-color:#fdba74;box-shadow:0 0 0 3px rgba(251,146,60,.1)}.password-panel .field{margin-top:13px}.password-rules{margin:12px 0;display:flex;gap:12px;color:#98a2b3;font-size:11px}.password-rules text::before{content:'○';margin-right:4px}.password-rules text.ok{color:#027a48}.password-rules text.ok::before{content:'✓'}.secondary-btn{width:100%;color:var(--es-primary);font-weight:600;background:#fff;border:1px solid #c7d7fe}.security-note{padding:16px;color:#475467;background:#f8fafc;border:1px solid var(--es-border-soft);border-radius:12px}.security-note text{display:block}.security-note text:first-child{font-size:12px;font-weight:700}.security-note text:last-child{margin-top:6px;font-size:11px;line-height:1.65}
@media(max-width:950px){.profile-grid{grid-template-columns:1fr}}@media(max-width:767px){.first-login-alert{align-items:flex-start;flex-wrap:wrap}.first-login-alert button{margin-left:45px}.panel{padding:17px}.saved-grid,.field-grid{grid-template-columns:1fr}.saved-grid>view{border-right:0!important;border-bottom:1px solid var(--es-border-soft)!important}.saved-grid>view:last-child{border-bottom:0!important}.form-actions{align-items:flex-start;flex-direction:column}.form-actions .primary-btn{width:100%}.status-chip{height:32px}.privacy-tag{display:none}}
</style>
