<template>
  <WorkbenchShell role="worker" active="wallet" title="我的钱包" subtitle="查看服务收入、提现进度和资金变动记录">
    <template #actions><view class="realname-chip" :class="{approved:realnameApproved}"><view/><text>{{ realnameApproved ? '实名已通过' : realnameStatusText(realnameStatus) }}</text></view></template>
    <view v-if="balanceFen < 0" class="negative-alert"><view>!</view><view><text>当前余额为负</text><text>可能由退款追佣或人工调账产生，请在流水中查看原因；余额恢复前无法提现。</text></view></view>
    <view class="summary-grid">
      <view class="summary-card primary"><view class="summary-icon">¥</view><text>可提现余额</text><text>¥{{ fenToYuan(balanceFen) }}</text><text>{{ wallet.freezeWithdrawal ? '提现功能已冻结' : '到账后可申请提现' }}</text></view>
      <view class="summary-card"><view class="summary-icon pending">时</view><text>提现处理中</text><text>¥{{ fenToYuan(wallet.pendingWithdrawFen) }}</text><text>{{ pendingCount }} 笔正在处理</text></view>
      <view class="summary-card"><view class="summary-icon income">收</view><text>累计服务收入</text><text>¥{{ fenToYuan(grossIncomeFen) }}</text><text>按正向钱包流水统计</text></view>
    </view>

    <view class="wallet-grid">
      <view class="panel transactions-panel"><view class="panel-head"><view><text class="panel-title">资金流水</text><text class="panel-desc">佣金、提现和退款追佣均有记录</text></view><text>{{ transactions.length }} 条</text></view>
        <view v-if="transactions.length" class="transaction-list"><view v-for="transaction in transactions" :key="transaction._id||transaction.id" class="transaction-row"><view class="transaction-symbol" :class="{negative:Number(transaction.amountFen)<0}">{{ Number(transaction.amountFen)<0?'−':'+' }}</view><view class="transaction-copy"><text>{{ transactionTypeText(transaction.type) }}</text><text>{{ formatDateTime(transaction.createdAt) }}<template v-if="transaction.remark"> · {{ transaction.remark }}</template></text></view><text class="transaction-amount" :class="{negative:Number(transaction.amountFen)<0}">{{ Number(transaction.amountFen)>=0?'+':'' }}¥{{ fenToYuan(transaction.amountFen) }}</text></view></view>
        <view v-else class="empty-state"><view>账</view><text>暂无钱包流水</text><text>订单完成结算后，收入记录会显示在这里</text></view>
      </view>
      <view class="side-stack">
        <view class="panel withdraw-panel"><view class="panel-head"><view><text class="panel-title">申请提现</text><text class="panel-desc">最低 10 元，本周已申请 {{ usedWeekCount }}/3 次</text></view></view><label class="amount-field"><text>提现金额（元）</text><view><text>¥</text><input v-model="amountYuan" type="digit" placeholder="0.00" /></view></label><view class="quick-amounts"><button v-for="amount in quickAmounts" :key="amount" @click="amountYuan=String(amount)">¥{{ amount }}</button><button @click="fillAll">全部</button></view><view v-if="!realnameApproved" class="withdraw-hint">请先在“个人资料”完成实名认证，审核通过后才可提现。</view><button class="withdraw-button" :disabled="busy||!canWithdraw" @click="applyWithdraw">{{ busy?'提交中…':'确认提现' }}</button><text class="rule-note">提交后资金进入冻结状态，管理员审核并确认实际打款后完成结算。</text></view>
        <view class="panel history-panel"><view class="panel-head"><view><text class="panel-title">提现记录</text><text class="panel-desc">最近的申请和处理状态</text></view></view><view v-if="withdrawals.length"><view v-for="withdrawal in withdrawals.slice(0,5)" :key="withdrawal._id||withdrawal.id" class="withdrawal-row"><view><text>¥{{ fenToYuan(withdrawal.amountFen) }}</text><text>{{ formatDateTime(withdrawal.createdAt) }}</text></view><text class="withdrawal-status" :class="withdrawalTone(withdrawal.status)">{{ withdrawalStatusText(withdrawal.status) }}</text></view></view><view v-else class="compact-empty">暂无提现记录</view></view>
      </view>
    </view>
  </WorkbenchShell>
</template>

<script setup>
import { computed, ref } from 'vue';
import { onLoad } from '@dcloudio/uni-app';
import { api } from '../../api.js';
import { confirmAction, fenToYuan, guard, realnameStatusText, withdrawalStatusText } from '../../common.js';
import { formatDateTime, transactionTypeText } from '../../utils/display.js';
import WorkbenchShell from '../../components/WorkbenchShell.vue';

const MIN_WITHDRAW_FEN=1000;const wallet=ref({balanceFen:0,availableFen:0,pendingWithdrawFen:0,withdrawnFen:0});const withdrawals=ref([]);const transactions=ref([]);const amountYuan=ref('');const realnameStatus=ref('UNSUBMITTED');const busy=ref(false);const quickAmounts=[10,50,100];
const balanceFen=computed(()=>Number(wallet.value.balanceFen!=null?wallet.value.balanceFen:(wallet.value.availableFen||0)));const pendingCount=computed(()=>withdrawals.value.filter((item)=>['PENDING_REVIEW','REVIEWING','APPROVED','PAYING'].includes(item.status)).length);const usedWeekCount=computed(()=>withdrawals.value.length);const grossIncomeFen=computed(()=>transactions.value.filter((item)=>Number(item.amountFen)>0&&['COMMISSION','ADJUST_ADD'].includes(item.type)).reduce((sum,item)=>sum+Number(item.amountFen||0),0));const realnameApproved=computed(()=>realnameStatus.value==='APPROVED');const requestedFen=computed(()=>Math.round(Number(amountYuan.value)*100));const canWithdraw=computed(()=>realnameApproved.value&&!wallet.value.freezeWithdrawal&&balanceFen.value>=MIN_WITHDRAW_FEN&&requestedFen.value>=MIN_WITHDRAW_FEN&&requestedFen.value<=balanceFen.value);
async function load(){try{const[w,list,txs,profile]=await Promise.all([api.getWallet(),api.listWithdrawals(),api.walletTransactions().catch(()=>[]),api.getProfile().catch(()=>({}))]);if(w)wallet.value=w;withdrawals.value=Array.isArray(list)?list:[];transactions.value=(Array.isArray(txs)?txs:[]).slice().sort((a,b)=>Number(b.createdAt||0)-Number(a.createdAt||0));realnameStatus.value=profile?.realnameStatus||'UNSUBMITTED';}catch(error){uni.showToast({title:error.message||'钱包加载失败',icon:'none'});}}
function fillAll(){amountYuan.value=balanceFen.value>0?fenToYuan(balanceFen.value):'';}function withdrawalTone(status){if(status==='PAID')return'success';if(['REJECTED','PAY_FAILED'].includes(status))return'danger';return'pending';}
async function applyWithdraw(){const amountFen=requestedFen.value;if(!realnameApproved.value){uni.showToast({title:'请先完成实名认证',icon:'none'});return;}if(!amountFen||amountFen<MIN_WITHDRAW_FEN){uni.showToast({title:'最低提现 10 元',icon:'none'});return;}if(amountFen>balanceFen.value){uni.showToast({title:'提现金额不能超过可用余额',icon:'none'});return;}const confirmed=await confirmAction({title:'确认提现申请',content:`确认申请提现 ¥${fenToYuan(amountFen)}？提交后该金额将被冻结，等待管理员审核。`,confirmText:'确认提现'});if(!confirmed)return;busy.value=true;try{await api.applyWithdrawal(amountFen);amountYuan.value='';uni.showToast({title:'已提交，等待管理员审核',icon:'success'});await load();}catch(error){uni.showToast({title:error.message||'提现失败',icon:'none'});}finally{busy.value=false;}}
onLoad(()=>{if(!guard(['WORKER']))return;load();});
</script>

<style lang="scss" scoped>
.realname-chip{height:36px;padding:0 12px;display:flex;align-items:center;gap:8px;color:#b54708;font-size:12px;font-weight:600;background:#fffaeb;border-radius:999px}.realname-chip>view{width:8px;height:8px;background:var(--es-warning);border-radius:50%}.realname-chip.approved{color:#027a48;background:#ecfdf3}.realname-chip.approved>view{background:var(--es-success)}.negative-alert{margin-bottom:16px;padding:14px 16px;display:flex;gap:12px;color:#b42318;background:#fef3f2;border:1px solid #fecdca;border-radius:11px}.negative-alert>view:first-child{width:28px;height:28px;flex:none;display:flex;align-items:center;justify-content:center;color:#fff;font-weight:800;background:#f04438;border-radius:50%}.negative-alert text{display:block;font-size:12px}.negative-alert text:first-child{font-size:13px;font-weight:700}.negative-alert text:last-child{margin-top:4px;line-height:1.5}
.summary-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.summary-card{min-height:142px;padding:18px;display:grid;grid-template-columns:42px 1fr;grid-template-rows:auto auto auto;column-gap:12px;background:#fff;border:1px solid var(--es-border-soft);border-radius:14px;box-shadow:var(--es-glow)}.summary-icon{width:42px;height:42px;grid-row:1/4;display:flex;align-items:center;justify-content:center;color:#4338ca;font-size:16px;font-weight:800;background:#eef0ff;border-radius:12px}.summary-icon.pending{color:#b54708;background:#fffaeb}.summary-icon.income{color:#027a48;background:#ecfdf3}.summary-card>text:nth-child(2){color:var(--es-text-dim);font-size:12px}.summary-card>text:nth-child(3){margin-top:4px;font-size:25px;font-weight:750}.summary-card>text:last-child{margin-top:7px;color:var(--es-text-dim);font-size:11px}.wallet-grid{margin-top:16px;display:grid;grid-template-columns:minmax(0,1.5fr) minmax(320px,.75fr);gap:16px}.side-stack{display:flex;flex-direction:column;gap:16px}.panel{padding:20px;background:#fff;border:1px solid var(--es-border-soft);border-radius:14px}.panel-head{margin-bottom:14px;display:flex;justify-content:space-between;gap:12px}.panel-title,.panel-desc{display:block}.panel-title{font-size:15px;font-weight:700}.panel-desc,.panel-head>text{margin-top:4px;color:var(--es-text-dim);font-size:11px}
.transaction-row{min-height:68px;display:flex;align-items:center;gap:12px;border-bottom:1px solid var(--es-border-soft)}.transaction-row:last-child{border-bottom:0}.transaction-symbol{width:34px;height:34px;flex:none;display:flex;align-items:center;justify-content:center;color:#027a48;font-weight:800;background:#ecfdf3;border-radius:10px}.transaction-symbol.negative{color:#b42318;background:#fef3f2}.transaction-copy{min-width:0;flex:1}.transaction-copy text{display:block}.transaction-copy text:first-child{font-size:13px;font-weight:600}.transaction-copy text:last-child{margin-top:4px;overflow:hidden;color:var(--es-text-dim);font-size:11px;text-overflow:ellipsis;white-space:nowrap}.transaction-amount{color:#027a48;font-size:14px;font-weight:700}.transaction-amount.negative{color:#b42318}.empty-state{min-height:290px;display:flex;flex-direction:column;align-items:center;justify-content:center;color:var(--es-text-dim)}.empty-state>view{width:56px;height:56px;display:flex;align-items:center;justify-content:center;color:var(--es-primary);font-weight:700;background:#eef0ff;border-radius:18px}.empty-state text:nth-child(2){margin-top:13px;color:var(--es-text);font-size:14px;font-weight:600}.empty-state text:last-child{margin-top:5px;font-size:11px}
.amount-field>text{display:block;margin-bottom:8px;color:#344054;font-size:12px;font-weight:600}.amount-field>view{height:50px;padding:0 13px;display:flex;align-items:center;gap:8px;border:1px solid var(--es-border);border-radius:10px}.amount-field>view>text{font-size:20px;font-weight:700}.amount-field input{min-width:0;flex:1;height:48px;font-size:22px;font-weight:600}.quick-amounts{margin-top:10px;display:grid;grid-template-columns:repeat(4,1fr);gap:7px}.quick-amounts button{height:32px;margin:0;padding:0;color:#475467;font-size:11px;line-height:32px;background:#f8fafc;border:1px solid var(--es-border-soft);border-radius:7px}.withdraw-hint{margin-top:12px;padding:9px 10px;color:#b54708;font-size:11px;line-height:1.5;background:#fffaeb;border-radius:8px}.withdraw-button{width:100%;height:40px;margin:14px 0 0;color:#fff;font-size:13px;font-weight:600;line-height:40px;background:var(--es-primary);border-radius:9px}.withdraw-button[disabled]{color:#98a2b3;background:#eaecf0}.rule-note{display:block;margin-top:10px;color:var(--es-text-dim);font-size:10px;line-height:1.55}.withdrawal-row{min-height:56px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid var(--es-border-soft)}.withdrawal-row:last-child{border-bottom:0}.withdrawal-row>view text{display:block}.withdrawal-row>view text:first-child{font-size:13px;font-weight:650}.withdrawal-row>view text:last-child{margin-top:3px;color:var(--es-text-dim);font-size:10px}.withdrawal-status{padding:4px 8px;color:#b54708;font-size:10px;font-weight:600;background:#fffaeb;border-radius:999px}.withdrawal-status.success{color:#027a48;background:#ecfdf3}.withdrawal-status.danger{color:#b42318;background:#fef3f2}.compact-empty{padding:26px;text-align:center;color:var(--es-text-dim);font-size:12px}
@media(max-width:980px){.wallet-grid{grid-template-columns:1fr}}@media(max-width:767px){.summary-grid{grid-template-columns:1fr}.summary-card{min-height:112px}.panel{padding:16px}.transaction-copy text:last-child{max-width:190px}.realname-chip{height:32px}}
</style>
