<template>
  <view class="page-shell" :style="brandState.vars"><view class="mobile-canvas">
    <UiSkeleton v-if="loading" :count="3"/>
    <UiState v-else-if="errorMsg" title="订单加载失败" :description="errorMsg" action-text="重新加载" @action="loadOrder"/>
    <template v-else-if="order">
      <view class="status-hero"><view class="status-row"><view><text class="status-text">{{ order.statusText||statusText(order.status) }}</text><text class="status-desc">{{ statusDesc(order.status) }}</text></view><view class="status-mark"><view class="status-check"/></view></view></view>
      <view class="card flow-card"><view class="flow">
        <view v-for="(step,index) in steps" :key="step.key" class="step" :class="{done:index<=currentStage,current:index===currentStage}"><view class="dot">{{ index<currentStage?'✓':index+1 }}</view><text>{{ step.label }}</text></view>
      </view></view>
      <view class="card service-card"><view class="card-title"><text>服务信息</text><text class="copy-link" @click="copyOrderNo">复制订单号</text></view><view class="service-body"><image class="cover" :src="cover" mode="aspectFill"/><view class="service-copy"><text class="title">{{ title }}</text><text>订单号 {{ order.orderNo }}</text><text>下单时间 {{ order.createdAtText||formatDateTime(order.createdAt) }}</text></view></view><view class="amount-row"><text>订单金额</text><text>¥{{ fenToYuan(order.amountFen) }}</text></view></view>
      <view class="card assurance-card"><view><view class="assurance-icon"><view class="assurance-check"/></view><text>订单全程留痕</text></view><view><view class="assurance-icon shield"><view class="assurance-check"/></view><text>售后服务保障</text></view></view>
      <view class="card actions-card"><button v-if="canPay" class="primary-btn" @click="continuePay">继续支付</button><button class="secondary-btn" @click="onSubscribe">订阅状态通知</button><button v-if="canDispute" class="danger-link" @click="showDispute=!showDispute">{{ showDispute?'收起异议申请':'对本订单发起异议' }}</button></view>
      <view v-if="showDispute" class="card dispute-card"><text class="card-heading">发起异议</text><text class="form-help">请说明具体问题，客服将在提交后跟进。</text><textarea v-model="disputeContent" class="dispute-input" maxlength="500" placeholder="请输入问题描述（500 字以内）"/><text class="word-count">{{ disputeContent.length }}/500</text><button class="primary-btn" :disabled="disputeSubmitting" @click="submitDispute">{{ disputeSubmitting?'提交中…':'提交异议' }}</button></view>
      <button class="contact-btn" open-type="contact" :session-from="contactSession" @click="showH5Contact"><image src="/static/icons/headset.svg" mode="aspectFit"/><text>联系订单客服</text></button>
    </template>
  </view></view>
</template>

<script setup>
import { computed, ref } from 'vue';
import { onLoad, onShow } from '@dcloudio/uni-app';
import { api, ensureSession } from '../../api.js';
import { brandState } from '../../brand.js';
import { brandContact } from '../../brand-assets.js';
import { requestSubscribeMessage } from '../../subscribe.js';
import { statusText, statusDesc, fenToYuan, formatDateTime } from '../../client-utils.js';
import UiSkeleton from '../../components/UiSkeleton.vue'; import UiState from '../../components/UiState.vue';
const orderId=ref(''); const order=ref(null); const loading=ref(true); const errorMsg=ref(''); const showDispute=ref(false); const disputeContent=ref(''); const disputeSubmitting=ref(false);
const steps=[{key:'paid',label:'已支付'},{key:'accepted',label:'已受理'},{key:'assigned',label:'已接单'},{key:'service',label:'服务中'},{key:'complete',label:'已完成'}];
const stageMap={PENDING_PAYMENT:0,PENDING_ACCEPT:0,PENDING_GRAB:1,ASSIGN_PENDING:2,IN_SERVICE:3,PENDING_CONFIRM:4,SETTLED:4,DISPUTING:4,REFUNDING:4,REFUNDED:4,CANCELLED:0,CLOSED:0};
const currentStage=computed(()=>stageMap[order.value&&order.value.status]??0); const title=computed(()=>(order.value&&order.value.product&&order.value.product.title)||'服务订单'); const cover=computed(()=>(order.value&&order.value.product&&order.value.product.coverImage)||'/static/default-product.svg');
const allowed=computed(()=>order.value&&Array.isArray(order.value.allowedActions)?order.value.allowedActions:[]); const canPay=computed(()=>allowed.value.includes('PAY')||(order.value&&order.value.status==='PENDING_PAYMENT')); const canDispute=computed(()=>allowed.value.includes('SUBMIT_DISPUTE')||(order.value&&order.value.status==='SETTLED')); const contactSession=computed(()=>order.value?`{"orderNo":"${order.value.orderNo}"}`:'{"source":"order"}');
onLoad((query)=>{orderId.value=(query&&query.id)||'';loadOrder();}); onShow(()=>{try{uni.setNavigationBarTitle({title:(brandState.brand&&brandState.brand.name)||'订单详情'});}catch(e){/* 忽略 */}});
async function loadOrder(){loading.value=true;errorMsg.value='';try{await ensureSession();const data=await api.getMyOrder(orderId.value);if(!data||!(data.id||data.orderId||data._id))throw new Error('订单不存在');order.value=data;}catch(error){order.value=null;errorMsg.value=(error&&error.message)||'订单加载失败';}finally{loading.value=false;}}
async function continuePay(){try{await ensureSession();const product=order.value.product||{};const res=await api.h5Token(product.id||product._id);if(!res||!res.token)throw new Error('支付链接生成失败');const id=order.value.id||order.value.orderId||order.value._id;uni.navigateTo({url:`/pages/order/webview-shell?token=${encodeURIComponent(res.token)}&orderId=${encodeURIComponent(id)}`});}catch(error){uni.showToast({title:(error&&error.message)||'操作失败',icon:'none'});}}
function copyOrderNo(){uni.setClipboardData({data:order.value.orderNo,success:()=>uni.showToast({title:'订单号已复制',icon:'success'})});}
async function onSubscribe(){const ok=await requestSubscribeMessage(order.value.id||order.value.orderId||order.value._id);uni.showToast({title:ok?'已订阅通知':'已跳过',icon:'none'});}
async function submitDispute(){const content=(disputeContent.value||'').trim();if(!content){uni.showToast({title:'请填写异议描述',icon:'none'});return;}disputeSubmitting.value=true;try{await api.submitDispute({orderId:order.value.id||order.value.orderId||order.value._id,content,attachmentIds:[]});uni.showToast({title:'异议已提交',icon:'success'});showDispute.value=false;disputeContent.value='';await loadOrder();}catch(error){uni.showToast({title:(error&&error.message)||'提交失败',icon:'none'});}finally{disputeSubmitting.value=false;}}
function showH5Contact(){
  // #ifdef H5
  const contact=brandContact();const lines=[contact.serviceWechat&&`客服微信：${contact.serviceWechat}`,contact.servicePhone&&`客服电话：${contact.servicePhone}`,contact.serviceHours&&`服务时间：${contact.serviceHours}`].filter(Boolean);uni.showModal({title:'联系订单客服',content:lines.join('\n')||'请联系品牌客服并提供订单号',showCancel:false});
  // #endif
}
</script>

<style lang="scss" scoped>
.page-shell{min-height:100vh;background:#e9edf5}.mobile-canvas{min-height:100vh;padding:24rpx 24rpx calc(60rpx + env(safe-area-inset-bottom));background:var(--brand-bg)}.status-hero{margin:-24rpx -24rpx 20rpx;padding:44rpx 32rpx 62rpx;color:#fff;background:linear-gradient(135deg,#232b62,var(--brand-primary),var(--brand-secondary))}.status-row{display:flex;align-items:center;justify-content:space-between}.status-text{display:block;font-size:42rpx;font-weight:800}.status-desc{display:block;max-width:520rpx;margin-top:10rpx;font-size:24rpx;line-height:1.5;opacity:.82}.status-mark{width:76rpx;height:76rpx;position:relative;flex:none;border:4rpx solid rgba(255,255,255,.7);border-radius:50%}.status-mark i{position:absolute;left:18rpx;top:31rpx;width:16rpx;height:4rpx;background:#fff;transform:rotate(43deg)}.status-mark i::after{content:'';position:absolute;left:12rpx;bottom:0;width:28rpx;height:4rpx;background:#fff;transform:rotate(-86deg);transform-origin:left}
.card{margin-bottom:20rpx;padding:26rpx;background:#fff;border-radius:24rpx;box-shadow:var(--shadow-card)}.flow-card{position:relative;margin-top:-48rpx}.flow{display:flex;justify-content:space-between}.step{position:relative;flex:1;display:flex;flex-direction:column;align-items:center;gap:10rpx;color:var(--color-text-tertiary);font-size:20rpx}.step:not(:last-child)::after{content:'';position:absolute;left:62%;right:-38%;top:21rpx;height:3rpx;background:#e4e7ec}.step.done:not(:last-child)::after{background:var(--brand-primary)}.dot{width:44rpx;height:44rpx;position:relative;z-index:1;display:flex;align-items:center;justify-content:center;color:#98a2b3;font-size:21rpx;background:#f2f4f7;border-radius:50%}.step.done .dot{color:#fff;background:var(--brand-primary)}.step.current text{color:var(--brand-primary);font-weight:700}
.card-title{display:flex;align-items:center;justify-content:space-between}.card-title>text:first-child,.card-heading{font-size:30rpx;font-weight:800}.copy-link{color:var(--brand-primary);font-size:23rpx}.service-body{margin-top:22rpx;display:flex;gap:20rpx}.cover{width:150rpx;height:116rpx;flex:none;border-radius:16rpx}.service-copy{min-width:0;flex:1}.service-copy .title{display:block;overflow:hidden;font-size:28rpx;font-weight:700;text-overflow:ellipsis;white-space:nowrap}.service-copy>text:not(.title){display:block;margin-top:9rpx;color:var(--color-text-tertiary);font-size:21rpx}.amount-row{margin-top:22rpx;padding-top:20rpx;display:flex;align-items:center;justify-content:space-between;border-top:1rpx solid var(--color-border);font-size:24rpx}.amount-row text:last-child{color:var(--brand-primary);font-size:34rpx;font-weight:800}
.assurance-card{display:grid;grid-template-columns:1fr 1fr}.assurance-card>view{display:flex;align-items:center;justify-content:center;gap:12rpx;color:var(--color-text-secondary);font-size:22rpx}.assurance-card>view:first-child{border-right:1rpx solid var(--color-border)}.assurance-icon{width:34rpx;height:34rpx;position:relative;border:3rpx solid var(--color-success);border-radius:50%}.assurance-icon i{position:absolute;left:7rpx;top:13rpx;width:8rpx;height:3rpx;background:var(--color-success);transform:rotate(40deg)}.assurance-icon i::after{content:'';position:absolute;left:6rpx;bottom:0;width:13rpx;height:3rpx;background:var(--color-success);transform:rotate(-80deg);transform-origin:left}.assurance-icon.shield{border-color:var(--brand-primary)}.assurance-icon.shield i,.assurance-icon.shield i::after{background:var(--brand-primary)}
.actions-card button,.dispute-card button{height:84rpx;margin-top:14rpx;font-size:27rpx;line-height:84rpx;border-radius:42rpx}.primary-btn{color:#fff;background:var(--brand-primary)}.secondary-btn{color:var(--brand-primary);background:var(--color-primary-soft)}.danger-link{color:var(--color-danger);background:transparent}.form-help{display:block;margin-top:8rpx;color:var(--color-text-secondary);font-size:23rpx}.dispute-input{width:100%;height:220rpx;margin-top:20rpx;padding:20rpx;font-size:26rpx;background:#f8f9fc;border:1rpx solid var(--color-border);border-radius:16rpx}.word-count{display:block;margin-top:8rpx;text-align:right;color:var(--color-text-tertiary);font-size:21rpx}.contact-btn{height:88rpx;margin-top:8rpx;display:flex;align-items:center;justify-content:center;gap:10rpx;color:var(--brand-primary);font-size:27rpx;line-height:88rpx;background:#fff;border:1rpx solid var(--brand-primary);border-radius:44rpx}.contact-btn image{width:36rpx;height:36rpx}
@media(min-width:480px){.mobile-canvas{width:480px;margin:0 auto;box-shadow:0 0 36px rgba(16,24,40,.08)}}
.status-check{position:absolute;left:18rpx;top:31rpx;width:16rpx;height:4rpx;background:#fff;transform:rotate(43deg)}.status-check::after{content:'';position:absolute;left:12rpx;bottom:0;width:28rpx;height:4rpx;background:#fff;transform:rotate(-86deg);transform-origin:left}.assurance-check{position:absolute;left:7rpx;top:13rpx;width:8rpx;height:3rpx;background:var(--color-success);transform:rotate(40deg)}.assurance-check::after{content:'';position:absolute;left:6rpx;bottom:0;width:13rpx;height:3rpx;background:var(--color-success);transform:rotate(-80deg);transform-origin:left}.assurance-icon.shield .assurance-check,.assurance-icon.shield .assurance-check::after{background:var(--brand-primary)}
</style>
